import dns from "node:dns/promises";
dns.setServers(["1.1.1.1"]);
import mongoose from 'mongoose';
import dotenv from 'dotenv';
import bcrypt from 'bcryptjs';
import User from './models/User.js';
import Product from './models/Product.js';
import Category from './models/Category.js';
import Order from './models/Order.js';
import CustomOrder from './models/CustomOrder.js';
import Review from './models/Review.js';
import ContactMessage from './models/ContactMessage.js';
import { connectDB } from './config/db.js';

dotenv.config();

export const seedData = async () => {
  try {
    // Clear existing collections
    await User.deleteMany({});
    await Product.deleteMany({});
    await Category.deleteMany({});
    await Order.deleteMany({});
    await CustomOrder.deleteMany({});
    await Review.deleteMany({});
    await ContactMessage.deleteMany({});

    console.log('🧹 Existing database records cleared.');

    // 1. Create Users
    const adminUser = await User.create({
      name: 'Manmeet Kaur (Admin)',
      email: process.env.ADMIN_EMAIL || 'kmeet7270@gmail.com',
      password: process.env.ADMIN_INITIAL_PASSWORD || 'Admin@1234',
      phone: '+91 6239661708',
      role: 'admin',
      addresses: [
        {
          street: 'VPO Tughalwal, Near Harchowal',
          city: 'Gurdaspur',
          state: 'Punjab',
          postalCode: '143527',
          country: 'India',
          isDefault: true,
        },
      ],
    });

    const demoCustomer = await User.create({
      name: 'Simran Sharma',
      email: 'customer@gmail.com',
      password: process.env.CUSTOMER_INITIAL_PASSWORD || 'Customer@1234',
      phone: '+91 98123 45678',
      role: 'customer',
      addresses: [
        {
          street: 'Flat 402, Rosewood Heights, MG Road',
          city: 'Delhi',
          state: 'Delhi',
          postalCode: '110001',
          country: 'India',
          isDefault: true,
        },
      ],
    });

    console.log('👤 Admin & Customer accounts initialized.');

    // 2. Create Categories
    const categoriesData = [
      {
        name: 'Handmade Embroidery',
        slug: 'handmade-embroidery',
        description: 'Delicate floral hoops, personalized wedding calendar hoops, and intricate thread work.',
        image: 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?auto=format&fit=crop&w=800&q=80',
        iconName: 'Scissors',
        isFeatured: true,
      },
      {
        name: 'Resin Art',
        slug: 'resin-art',
        description: 'Glossy ocean wave wall clocks, geode platters, floral preserved preservation blocks & coasters.',
        image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
        iconName: 'Sparkles',
        isFeatured: true,
      },
      {
        name: 'Fabric Painting',
        slug: 'fabric-painting',
        description: 'Custom hand-painted organza dupattas, canvas tote bags, denim jackets, and cushion covers.',
        image: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80',
        iconName: 'Palette',
        isFeatured: true,
      },
      {
        name: 'Portraits',
        slug: 'portraits',
        description: 'Hand-drawn charcoal sketches, vibrant watercolor couple portraits, and realistic digital oil art.',
        image: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=800&q=80',
        iconName: 'Image',
        isFeatured: true,
      },
      {
        name: 'Handmade Gifts',
        slug: 'handmade-gifts',
        description: 'Heartfelt explosion boxes, customized photo scrapbooks, love hampers, and wooden photo plaques.',
        image: 'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?auto=format&fit=crop&w=800&q=80',
        iconName: 'Gift',
        isFeatured: true,
      },
      {
        name: 'Customized Gifts',
        slug: 'customized-gifts',
        description: 'Personalized name lamps, customized calendar frames, couple nameplates, and memory frames.',
        image: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=800&q=80',
        iconName: 'HeartHandshake',
        isFeatured: true,
      },
      {
        name: 'Handmade Jewellery',
        slug: 'handmade-jewellery',
        description: 'Lightweight polymer clay earrings, real pressed floral resin pendants, and beaded statement pieces.',
        image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80',
        iconName: 'Gem',
        isFeatured: true,
      },
      {
        name: 'Decorative Crafts',
        slug: 'decorative-crafts',
        description: 'Boho macrame wall hangings, lippan art mirror wall plates, and handcrafted festive decor.',
        image: 'https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&w=800&q=80',
        iconName: 'Layers',
        isFeatured: true,
      },
    ];

    const createdCategories = await Category.insertMany(categoriesData);
    console.log(`📁 ${createdCategories.length} Categories seeded.`);

    // 3. Create 24 Handcrafted Boutique Products
    const productsData = [
      // 1. Embroidery
      {
        name: 'Personalized Couple Wedding Embroidery Hoop',
        slug: 'personalized-couple-wedding-embroidery-hoop',
        tagline: 'Timeless wedding keepsake embroidered with love & silk threads',
        description: 'Commemorate sacred nuptials or anniversary milestones with our signature hand-embroidered wedding hoop. Handcrafted with DMC French stranded cotton threads on premium linen canvas, featuring customized bride & groom names, wedding date, floral wreath and delicate French knots.',
        category: 'Handmade Embroidery',
        price: 1899,
        originalPrice: 2499,
        discountPercent: 24,
        rating: 4.9,
        numReviews: 28,
        images: [
          'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?auto=format&fit=crop&w=1000&q=80',
          'https://images.unsplash.com/photo-1607344645866-009c320c5ab8?auto=format&fit=crop&w=1000&q=80',
          'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?auto=format&fit=crop&w=1000&q=80',
        ],
        featuredImage: 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?auto=format&fit=crop&w=1000&q=80',
        materials: ['Beechwood Hoop', 'Organic Linen Cloth', 'DMC Cotton Embroidery Floss', 'Satin Ribbon'],
        dimensions: '10 inch diameter (25.4 cm)',
        leadTimeDays: 4,
        isCustomizable: true,
        customizationNote: 'Specify Bride & Groom names, date, and preferred floral color theme at checkout.',
        inStock: true,
        countInStock: 12,
        isFeatured: true,
        isBestSeller: true,
        tags: ['embroidery', 'wedding', 'hoop art', 'personalized gift', 'anniversary'],
      },
      {
        name: 'Botanical Meadow French Knot Floral Hoop',
        slug: 'botanical-meadow-french-knot-floral-hoop',
        tagline: 'Pastel wildflowers blooming in intricate 3D hand embroidery',
        description: 'Bring the charm of a sunlit lavender meadow inside your home. Features raised 3D Brazilian cast-on stitches, roses, wild daisies, and woven wheel embroidery that feels soft to the touch.',
        category: 'Handmade Embroidery',
        price: 1450,
        originalPrice: 1800,
        discountPercent: 19,
        rating: 4.8,
        numReviews: 16,
        images: [
          'https://images.unsplash.com/photo-1607344645866-009c320c5ab8?auto=format&fit=crop&w=1000&q=80',
          'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?auto=format&fit=crop&w=1000&q=80',
        ],
        featuredImage: 'https://images.unsplash.com/photo-1607344645866-009c320c5ab8?auto=format&fit=crop&w=1000&q=80',
        materials: ['Natural Bamboo Hoop', 'Raw Cotton Muslin', 'Silk Blend Floss'],
        dimensions: '8 inch diameter',
        leadTimeDays: 3,
        isCustomizable: true,
        customizationNote: 'Add a handwritten quote or initials in the center wreath.',
        inStock: true,
        countInStock: 8,
        isFeatured: false,
        isBestSeller: false,
        tags: ['botanical', 'floral', 'embroidery', 'home decor', 'wall art'],
      },
      {
        name: 'Custom Baby Birth Announcement Hoop Art',
        slug: 'custom-baby-birth-announcement-hoop-art',
        tagline: 'Celebrate the arrival of your little angel with custom details',
        description: 'An adorable nursery keepsake stitched with baby’s name, date of birth, birth time, weight, and zodiac motif. Framed in a smooth wooden hoop adorned with pearl beads and lace edging.',
        category: 'Handmade Embroidery',
        price: 1650,
        originalPrice: 2100,
        discountPercent: 21,
        rating: 5.0,
        numReviews: 34,
        images: [
          'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?auto=format&fit=crop&w=1000&q=80',
          'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?auto=format&fit=crop&w=1000&q=80',
        ],
        featuredImage: 'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?auto=format&fit=crop&w=1000&q=80',
        materials: ['Cotton Canvas', 'Imported Threads', 'Lace Border', 'Solid Wood Hoop'],
        dimensions: '9 inch diameter',
        leadTimeDays: 4,
        isCustomizable: true,
        customizationNote: 'Provide Baby Name, Date, Time, Weight, and parents names.',
        inStock: true,
        countInStock: 15,
        isFeatured: true,
        isBestSeller: false,
        tags: ['baby shower', 'birth announcement', 'nursery decor', 'embroidery'],
      },

      // 2. Resin Art
      {
        name: 'Ocean Wave Luxury Resin Wall Clock',
        slug: 'ocean-wave-luxury-resin-wall-clock',
        tagline: 'Deep Caribbean azure sea waves with realistic foaming surf & silent sweep',
        description: 'Immerse your space in the tranquil aura of the shoreline. Multi-layered crystal-clear epoxy resin poured over solid MDF base, featuring crushed natural crystals, real white seafoam cell effect, and polished gold Roman numerals. Powered by a high-torque silent quartz mechanism.',
        category: 'Resin Art',
        price: 3499,
        originalPrice: 4500,
        discountPercent: 22,
        rating: 4.9,
        numReviews: 42,
        images: [
          'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1000&q=80',
          'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1000&q=80',
        ],
        featuredImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1000&q=80',
        materials: ['High-Gloss Epoxy Resin', 'MDF Board', 'Real Quartz Crystals', 'Silent German Movement'],
        dimensions: '14 inch diameter (35.5 cm)',
        leadTimeDays: 5,
        isCustomizable: true,
        customizationNote: 'Choose between Roman or Standard numbers, and Gold or Silver hands.',
        inStock: true,
        countInStock: 6,
        isFeatured: true,
        isBestSeller: true,
        tags: ['resin art', 'wall clock', 'ocean art', 'luxury home decor', 'statement piece'],
      },
      {
        name: 'Real Rose Petal & 24K Gold Leaf Resin Platter Set',
        slug: 'real-rose-petal-24k-gold-leaf-resin-platter-set',
        tagline: 'Hand-poured serving tray with 4 matching geode coasters',
        description: 'Preserved real crimson rose petals and shimmering 24-karat gold leaf flakes suspended in ultra-clear food-safe epoxy resin. Includes sturdy gold brass handles and 4 matching coasters with hand-gilded edges.',
        category: 'Resin Art',
        price: 2299,
        originalPrice: 2999,
        discountPercent: 23,
        rating: 4.8,
        numReviews: 19,
        images: [
          'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=1000&q=80',
          'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1000&q=80',
        ],
        featuredImage: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=1000&q=80',
        materials: ['Food-Grade Epoxy Resin', 'Preserved Rose Petals', 'Brass Handles', 'Gold Leaf Foil'],
        dimensions: 'Platter: 12x8 inches, Coasters: 4 inch each',
        leadTimeDays: 4,
        isCustomizable: true,
        customizationNote: 'Custom floral inclusions like baby breath, marigold, or wedding varmala flowers available.',
        inStock: true,
        countInStock: 9,
        isFeatured: false,
        isBestSeller: false,
        tags: ['resin tray', 'coasters', 'gold leaf', 'dining decor', 'housewarming'],
      },
      {
        name: 'Varmala Wedding Flower Resin Preservation Hexagon Block',
        slug: 'varmala-wedding-flower-resin-preservation-hexagon-block',
        tagline: 'Turn your sacred wedding garlands into forever glowing crystal art',
        description: 'Don’t let your wedding varmalas dry out in a closet. Send us your special flowers, and our master resin artist will freeze-dry, restore, and cast them inside an heirloom diamond-cut hexagon resin monolith with an integrated warm LED wooden base.',
        category: 'Resin Art',
        price: 4899,
        originalPrice: 5999,
        discountPercent: 18,
        rating: 5.0,
        numReviews: 53,
        images: [
          'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1000&q=80',
          'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1000&q=80',
        ],
        featuredImage: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1000&q=80',
        materials: ['UV-Resistant Cast Resin', 'Preserved Flowers', 'Teak Wood LED Stand'],
        dimensions: '8 x 8 x 2 inches',
        leadTimeDays: 7,
        isCustomizable: true,
        customizationNote: 'Includes personalized engraved metallic plate with couple names & date.',
        inStock: true,
        countInStock: 20,
        isFeatured: true,
        isBestSeller: true,
        tags: ['varmala preservation', 'wedding keepsake', 'resin art', 'flower preservation'],
      },

      // 3. Fabric Painting
      {
        name: 'Hand-Painted Wild Lotus Pure Organza Dupatta',
        slug: 'hand-painted-wild-lotus-pure-organza-dupatta',
        tagline: 'Art you can wear: hand-painted botanical watercolors on sheer organza',
        description: 'Each stroke is painted by hand using permanent textile metallic and watercolor pigments on premium sheer ivory organza. Finished with hand-stitched scallop lace borders and subtle gold shimmer highlights.',
        category: 'Fabric Painting',
        price: 2799,
        originalPrice: 3500,
        discountPercent: 20,
        rating: 4.9,
        numReviews: 31,
        images: [
          'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=1000&q=80',
          'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1000&q=80',
        ],
        featuredImage: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=1000&q=80',
        materials: ['Pure Silk Organza', 'Permanent Fabric Acrylics', 'Gota Lace Borders'],
        dimensions: '2.5 Meters length, 36 inch width',
        leadTimeDays: 6,
        isCustomizable: true,
        customizationNote: 'Custom floral motifs (Sunflower, Peony, Gulmohar) or color palettes on request.',
        inStock: true,
        countInStock: 5,
        isFeatured: true,
        isBestSeller: true,
        tags: ['dupatta', 'organza', 'fabric painting', 'ethnic wear', 'hand painted'],
      },
      {
        name: 'Bespoke Hand-Painted Denim Jacket (Custom Art)',
        slug: 'bespoke-hand-painted-denim-jacket',
        tagline: 'Expressive back-patch painting on heavy vintage washed denim',
        description: 'Send us your idea or choose our signature starry night mandala portrait. Hand-painted with multi-layer waterproof heat-cured textile mediums that will not fade or crack even after gentle washes.',
        category: 'Fabric Painting',
        price: 3899,
        originalPrice: 4999,
        discountPercent: 22,
        rating: 4.9,
        numReviews: 18,
        images: [
          'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1000&q=80',
          'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=1000&q=80',
        ],
        featuredImage: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1000&q=80',
        materials: ['100% Cotton Denim', 'Textile Medium Acrylics', 'Varnish Sealant'],
        dimensions: 'Sizes S, M, L, XL, XXL available',
        leadTimeDays: 6,
        isCustomizable: true,
        customizationNote: 'Upload your reference portrait or quote for the back panel.',
        inStock: true,
        countInStock: 7,
        isFeatured: false,
        isBestSeller: false,
        tags: ['denim jacket', 'custom jacket', 'fabric painting', 'streetwear art'],
      },
      {
        name: 'Monstera & Sun Hand-Painted Heavy Canvas Tote Bag',
        slug: 'monstera-sun-hand-painted-canvas-tote-bag',
        tagline: 'Eco-friendly aesthetic everyday companion made with durable duck canvas',
        description: 'Spacious, reinforced tote bag hand-painted with earthy terracotta boho botanical foliage. Features an inner zippered pocket, magnetic snap button, and comfortable shoulder straps.',
        category: 'Fabric Painting',
        price: 899,
        originalPrice: 1199,
        discountPercent: 25,
        rating: 4.7,
        numReviews: 24,
        images: [
          'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=1000&q=80',
          'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?auto=format&fit=crop&w=1000&q=80',
        ],
        featuredImage: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=1000&q=80',
        materials: ['450 GSM Organic Cotton Duck Canvas', 'Eco-friendly non-toxic paint'],
        dimensions: '16 x 15 x 4 inches with 10 inch handle drop',
        leadTimeDays: 2,
        isCustomizable: true,
        customizationNote: 'Add your custom initial or name calligraphed on the front.',
        inStock: true,
        countInStock: 25,
        isFeatured: false,
        isBestSeller: false,
        tags: ['tote bag', 'canvas bag', 'hand painted', 'eco friendly'],
      },

      // 4. Portraits
      {
        name: 'Handcrafted Charcoal Realism Couple Portrait',
        slug: 'handcrafted-charcoal-realism-couple-portrait',
        tagline: 'Deep expressive monochrome tones framed under museum-grade glass',
        description: 'Turn your favorite photograph into a breathtaking fine-art charcoal drawing. Drawn meticulously with Faber-Castell & Nitram Willow charcoal on heavy 300 GSM acid-free archival Fabriano paper. Arrives framed in elegant matte black wood.',
        category: 'Portraits',
        price: 2999,
        originalPrice: 3800,
        discountPercent: 21,
        rating: 5.0,
        numReviews: 47,
        images: [
          'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1000&q=80',
          'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?auto=format&fit=crop&w=1000&q=80',
        ],
        featuredImage: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1000&q=80',
        materials: ['Fabriano 300 GSM Archival Paper', 'Nitram Willow Charcoal', 'Solid Wood Frame', 'Anti-glare Glass'],
        dimensions: 'A3 Size (12 x 16 inches) with Frame',
        leadTimeDays: 5,
        isCustomizable: true,
        customizationNote: 'Upload your high-resolution couple photo during checkout or via WhatsApp.',
        inStock: true,
        countInStock: 10,
        isFeatured: true,
        isBestSeller: true,
        tags: ['portrait', 'charcoal sketch', 'couple portrait', 'framed art', 'anniversary gift'],
      },
      {
        name: 'Dreamy Watercolor Family / Pet Illustration',
        slug: 'dreamy-watercolor-family-pet-illustration',
        tagline: 'Vibrant fluid watercolor washes capturing the warmth of your loved ones',
        description: 'Hand-painted with Winsor & Newton artist watercolors on 100% cotton cold-press paper. Perfect for family portraits, newborn milestones, or loving pet memorials. Includes soft pastel floral background detailing.',
        category: 'Portraits',
        price: 2499,
        originalPrice: 3200,
        discountPercent: 22,
        rating: 4.9,
        numReviews: 29,
        images: [
          'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1000&q=80',
          'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=1000&q=80',
        ],
        featuredImage: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1000&q=80',
        materials: ['Arches 300 GSM Watercolor Paper', 'Winsor & Newton Artist Pigments', 'Natural Oak Frame'],
        dimensions: '10 x 12 inches framed',
        leadTimeDays: 4,
        isCustomizable: true,
        customizationNote: 'You can combine individual photos into one single merged family portrait painting.',
        inStock: true,
        countInStock: 8,
        isFeatured: false,
        isBestSeller: false,
        tags: ['watercolor portrait', 'pet portrait', 'family illustration', 'custom painting'],
      },
      {
        name: 'Royal Heritage Oil Palette Knife Portrait on Canvas',
        slug: 'royal-heritage-oil-palette-knife-portrait-on-canvas',
        tagline: 'Rich textured impasto oil painting on stretched Italian linen canvas',
        description: 'For those seeking magnificent grandeur. Textured oil paint applied with palette knife techniques creating luminous highlights and lifelike depth. Ready to hang without framing needed.',
        category: 'Portraits',
        price: 4999,
        originalPrice: 6500,
        discountPercent: 23,
        rating: 5.0,
        numReviews: 14,
        images: [
          'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1000&q=80',
          'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1000&q=80',
        ],
        featuredImage: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1000&q=80',
        materials: ['Stretched Canvas on Pine Stretcher Bars', 'Old Holland Artist Oils', 'Gloss Damar Varnish'],
        dimensions: '16 x 20 inches',
        leadTimeDays: 7,
        isCustomizable: true,
        customizationNote: 'Provide photo for custom portrait execution.',
        inStock: true,
        countInStock: 4,
        isFeatured: false,
        isBestSeller: false,
        tags: ['oil painting', 'canvas portrait', 'palette knife', 'fine art'],
      },

      // 5. Handmade Gifts
      {
        name: 'Surprise Luxury 4-Layer Memory Explosion Box',
        slug: 'surprise-luxury-4-layer-memory-explosion-box',
        tagline: 'Unfolds into 24 interactive photo pockets, waterfall cards & secret gift box',
        description: 'When the lid is removed, all 4 layers cascade open into an awe-inspiring photo album! Handcrafted with heavy 350 GSM craft paper, featuring magnetic closures, slider cards, endless folding cards, and a center compartment for jewelry or chocolates.',
        category: 'Handmade Gifts',
        price: 1599,
        originalPrice: 2199,
        discountPercent: 27,
        rating: 4.9,
        numReviews: 39,
        images: [
          'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?auto=format&fit=crop&w=1000&q=80',
          'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=1000&q=80',
        ],
        featuredImage: 'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?auto=format&fit=crop&w=1000&q=80',
        materials: ['Matte Craft Board', 'Textured Metallic Paper', 'Silk Bow', 'Acid-Free Photo Prints'],
        dimensions: 'Closed: 6x6x6 inches, Open: 18x18 inches',
        leadTimeDays: 3,
        isCustomizable: true,
        customizationNote: 'Includes high-definition printing & mounting of 20 to 24 of your selected photos.',
        inStock: true,
        countInStock: 18,
        isFeatured: true,
        isBestSeller: true,
        tags: ['explosion box', 'photo gift', 'birthday gift', 'surprise box', 'anniversary'],
      },
      {
        name: 'Vintage Wooden Memory Photo Scrapbook Album',
        slug: 'vintage-wooden-memory-photo-scrapbook-album',
        tagline: 'Laser-engraved wooden cover with 30 black kraft card pages',
        description: 'A timeless treasure chest for your adventures. Bound with vintage brass rings, featuring custom carved couple names or quote on natural wood cover. Includes photo corner stickers and metallic calligraphy gel pens.',
        category: 'Handmade Gifts',
        price: 1399,
        originalPrice: 1799,
        discountPercent: 22,
        rating: 4.8,
        numReviews: 21,
        images: [
          'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=1000&q=80',
          'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?auto=format&fit=crop&w=1000&q=80',
        ],
        featuredImage: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=1000&q=80',
        materials: ['Birch Plywood Engraved Cover', '300 GSM Black Kraft Paper', 'Brass Binder Rings'],
        dimensions: '10 x 8 inches (Holds up to 80 photos)',
        leadTimeDays: 3,
        isCustomizable: true,
        customizationNote: 'Custom wood laser engraving of names, anniversary date, or personal quote.',
        inStock: true,
        countInStock: 14,
        isFeatured: false,
        isBestSeller: false,
        tags: ['scrapbook', 'wooden album', 'memory book', 'vintage gift'],
      },
      {
        name: 'Illuminated Message in a Glass Bottle with Fairy Lights',
        slug: 'illuminated-message-in-a-glass-bottle-fairy-lights',
        tagline: 'A romantic handwritten parchment scroll glowing inside antique glass',
        description: 'Capture pure poetic romance. Your personal love letter or gratitude message handwritten in calligraphy on burnt-edge aged parchment, wrapped in leather cord and suspended with micro LED fairy lights inside a corked glass vial.',
        category: 'Handmade Gifts',
        price: 749,
        originalPrice: 999,
        discountPercent: 25,
        rating: 4.8,
        numReviews: 17,
        images: [
          'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?auto=format&fit=crop&w=1000&q=80',
          'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1000&q=80',
        ],
        featuredImage: 'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?auto=format&fit=crop&w=1000&q=80',
        materials: ['Borosilicate Glass', 'Natural Cork', 'Aged Parchment', 'Copper Wire Fairy Lights'],
        dimensions: '8 inches height, 3 inches diameter',
        leadTimeDays: 2,
        isCustomizable: true,
        customizationNote: 'Send your customized message (up to 150 words) to be written on the scroll.',
        inStock: true,
        countInStock: 22,
        isFeatured: false,
        isBestSeller: false,
        tags: ['message in a bottle', 'romantic gift', 'fairy lights', 'handmade gift'],
      },

      // 6. Customized Gifts
      {
        name: 'Custom Acrylic Song Plaque with Wooden LED Base',
        slug: 'custom-acrylic-song-plaque-wooden-led-base',
        tagline: 'Your favorite Spotify song, scannable barcode, photo & custom message',
        description: 'Preserve that one song that defines your bond. High-definition laser printed on 4mm shatterproof cast acrylic. Scan the Spotify code with your phone camera to instantly play the music! Sits on an illuminated solid oak wood stand.',
        category: 'Customized Gifts',
        price: 1199,
        originalPrice: 1699,
        discountPercent: 29,
        rating: 4.9,
        numReviews: 61,
        images: [
          'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=1000&q=80',
          'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1000&q=80',
        ],
        featuredImage: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=1000&q=80',
        materials: ['Cast Optical Acrylic', 'Warm White LED Strip', 'Solid Oak Wood Base', 'USB Power Cable'],
        dimensions: '8 x 6 inches acrylic, 6 inch wooden base',
        leadTimeDays: 2,
        isCustomizable: true,
        customizationNote: 'Provide Song Name, Artist, Custom Photo, and optional timestamp.',
        inStock: true,
        countInStock: 30,
        isFeatured: true,
        isBestSeller: true,
        tags: ['acrylic plaque', 'music plaque', 'spotify gift', 'customized lamp', 'best seller'],
      },
      {
        name: 'Handcrafted Personalized Couple 3D Wooden Nameplate',
        slug: 'handcrafted-personalized-couple-3d-wooden-nameplate',
        tagline: 'Warm welcoming handcrafted teak finish board with raised brass lettering',
        description: 'Elevate your entrance with warm handcrafted charm. Weatherproof treated pinewood plank adorned with hand-painted resin floral accents, metallic brass lettering, and heavy brass hanging hooks.',
        category: 'Customized Gifts',
        price: 1999,
        originalPrice: 2600,
        discountPercent: 23,
        rating: 4.9,
        numReviews: 27,
        images: [
          'https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&w=1000&q=80',
          'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=1000&q=80',
        ],
        featuredImage: 'https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&w=1000&q=80',
        materials: ['Treated Teak Wood', 'Acrylic Mirror Gold Cutouts', 'Weatherproof PU Clear Coat'],
        dimensions: '14 x 8 x 1 inches',
        leadTimeDays: 4,
        isCustomizable: true,
        customizationNote: 'Provide Family Names / Flat Number to be custom fabricated.',
        inStock: true,
        countInStock: 11,
        isFeatured: false,
        isBestSeller: false,
        tags: ['nameplate', 'housewarming', 'wooden art', 'home entrance'],
      },
      {
        name: 'Personalized Constellation Star Map Night Light Frame',
        slug: 'personalized-constellation-star-map-night-light-frame',
        tagline: 'The exact alignment of the stars on the night your story began',
        description: 'Using astronomical star catalog algorithms, we render the exact celestial sky for your special date and coordinates (the night you met, your wedding night, or birth of your child). Embellished with backlighting LEDs in a deep shadowbox.',
        category: 'Customized Gifts',
        price: 1499,
        originalPrice: 1999,
        discountPercent: 25,
        rating: 5.0,
        numReviews: 35,
        images: [
          'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=1000&q=80',
          'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?auto=format&fit=crop&w=1000&q=80',
        ],
        featuredImage: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=1000&q=80',
        materials: ['Satin Archival Print', 'Solid Wood Shadowbox Frame', 'Warm LED Illumination'],
        dimensions: '9 x 12 inches framed',
        leadTimeDays: 3,
        isCustomizable: true,
        customizationNote: 'Enter Location (City), Date, Names, and custom bottom quote.',
        inStock: true,
        countInStock: 16,
        isFeatured: true,
        isBestSeller: false,
        tags: ['star map', 'custom gift', 'constellation', 'anniversary frame'],
      },

      // 7. Handmade Jewellery
      {
        name: 'Real Daisy & Gold Flake Botanical Resin Pendant',
        slug: 'real-daisy-gold-flake-botanical-resin-pendant',
        tagline: 'Hand-picked organic wild daisies preserved in crystal resin with 18K gold chain',
        description: 'Nature’s pure poetry captured around your neck. Each wild white daisy is hand-harvested, pressed for 3 weeks, and encased in anti-yellowing jeweler’s grade resin with 24K gold foil flakes. Comes with an anti-tarnish 18K gold-plated stainless steel chain in a velvet gift box.',
        category: 'Handmade Jewellery',
        price: 999,
        originalPrice: 1499,
        discountPercent: 33,
        rating: 4.9,
        numReviews: 44,
        images: [
          'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1000&q=80',
          'https://images.unsplash.com/photo-1607344645866-009c320c5ab8?auto=format&fit=crop&w=1000&q=80',
        ],
        featuredImage: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1000&q=80',
        materials: ['Real Pressed Wild Daisy', 'Jewelry Epoxy Resin', '18K Gold Plated Stainless Steel Chain (Hypoallergenic)'],
        dimensions: 'Pendant: 25mm diameter, Chain: 18 inches + 2 inch extender',
        leadTimeDays: 2,
        isCustomizable: false,
        customizationNote: 'Available in Gold or Silver chain finishes.',
        inStock: true,
        countInStock: 20,
        isFeatured: true,
        isBestSeller: true,
        tags: ['resin jewellery', 'flower pendant', 'botanical jewellery', 'necklace', 'handmade gift'],
      },
      {
        name: 'Sculpted Polymer Clay Terracotta Statement Earrings',
        slug: 'sculpted-polymer-clay-terracotta-statement-earrings',
        tagline: 'Ultra-lightweight artisan earrings with textured arch & brass charms',
        description: 'Weighing less than a coin! Hand-conditioned, sculpted, textured, and baked in small batches. Hypoallergenic titanium posts suitable for the most sensitive ears. Features warm terracotta, sage green, and brushed raw brass pendants.',
        category: 'Handmade Jewellery',
        price: 699,
        originalPrice: 999,
        discountPercent: 30,
        rating: 4.8,
        numReviews: 23,
        images: [
          'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1000&q=80',
          'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=1000&q=80',
        ],
        featuredImage: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1000&q=80',
        materials: ['Sculpey Premo Polymer Clay', 'Raw Brass Findings', 'Titanium Earring Posts'],
        dimensions: '2.4 inches drop length, 1.1 inch width',
        leadTimeDays: 2,
        isCustomizable: false,
        customizationNote: 'Available in clip-on options upon request.',
        inStock: true,
        countInStock: 15,
        isFeatured: false,
        isBestSeller: false,
        tags: ['clay earrings', 'handmade jewellery', 'boho earrings', 'lightweight'],
      },
      {
        name: 'Personalized Initial Bead & Freshwater Pearl Bracelet',
        slug: 'personalized-initial-bead-freshwater-pearl-bracelet',
        tagline: 'Genuine baroque pearls woven with customizable gold letter beads',
        description: 'Dainty, luxurious, and personal. Crafted with genuine natural cultured freshwater baroque pearls and 14k gold-filled alphabet beads that will not tarnish. Strung on durable Japanese braided nylon cord.',
        category: 'Handmade Jewellery',
        price: 849,
        originalPrice: 1199,
        discountPercent: 29,
        rating: 4.9,
        numReviews: 32,
        images: [
          'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1000&q=80',
          'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?auto=format&fit=crop&w=1000&q=80',
        ],
        featuredImage: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1000&q=80',
        materials: ['Genuine Freshwater Baroque Pearls', '14K Gold Filled Beads', 'Adjustable Lobster Clasp'],
        dimensions: 'Adjustable 6.5 inch to 8 inch wrist size',
        leadTimeDays: 2,
        isCustomizable: true,
        customizationNote: 'Select any 1 to 4 letter initials for your bracelet.',
        inStock: true,
        countInStock: 18,
        isFeatured: false,
        isBestSeller: false,
        tags: ['pearl bracelet', 'custom jewellery', 'initial bracelet', 'minimalist'],
      },

      // 8. Decorative Crafts
      {
        name: 'Boho Macrame Mandala Wall Hanging with Mirror',
        slug: 'boho-macrame-mandala-wall-hanging-mirror',
        tagline: 'Hand-knotted 100% organic cotton cord woven around a clear center mirror',
        description: 'Add instant cozy texture and Scandinavian bohemian warmth to your bedroom or entryway. Masterfully hand-knotted with over 200 meters of unbleached natural cotton rope, featuring intricate fringe tassels and reinforced metal ring support.',
        category: 'Decorative Crafts',
        price: 1799,
        originalPrice: 2399,
        discountPercent: 25,
        rating: 4.8,
        numReviews: 26,
        images: [
          'https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&w=1000&q=80',
          'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=1000&q=80',
        ],
        featuredImage: 'https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&w=1000&q=80',
        materials: ['100% Recycled Natural Cotton Rope', 'High-Definition Silver Mirror', 'Metal Ring Frame'],
        dimensions: 'Total diameter 16 inches, Mirror diameter 8 inches',
        leadTimeDays: 3,
        isCustomizable: true,
        customizationNote: 'Available in Cream Natural, Mustard, or Dusty Rose cord colors.',
        inStock: true,
        countInStock: 10,
        isFeatured: true,
        isBestSeller: false,
        tags: ['macrame mirror', 'boho decor', 'wall hanging', 'home decor', 'handmade craft'],
      },
      {
        name: 'Traditional Kutch Lippan Mud & Mirror Art Wall Plate',
        slug: 'traditional-kutch-lippan-mud-mirror-art-wall-plate',
        tagline: 'Authentic textured clay dough relief work studded with sparkling convex mirrors',
        description: 'An ancient heritage art form from the desert artisans of Gujarat, reimagined for modern luxury interiors. Intricate geometrical sacred patterns molded by hand in ceramic clay relief, painted in pure matte chalk paint, and studded with over 150 diamond & circular glass mirrors.',
        category: 'Decorative Crafts',
        price: 2199,
        originalPrice: 2899,
        discountPercent: 24,
        rating: 5.0,
        numReviews: 38,
        images: [
          'https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&w=1000&q=80',
          'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1000&q=80',
        ],
        featuredImage: 'https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&w=1000&q=80',
        materials: ['Water-Resistant MDF Base', 'Clay Ceramic Relief Compound', 'Real Glass Mirrors', 'Chalk Acrylic Finish'],
        dimensions: '12 inch diameter round plate',
        leadTimeDays: 4,
        isCustomizable: true,
        customizationNote: 'Custom color base (Ivory White, Royal Teal, Ochre Yellow, Terracotta Red).',
        inStock: true,
        countInStock: 8,
        isFeatured: false,
        isBestSeller: true,
        tags: ['lippan art', 'mirror art', 'traditional craft', 'wall decor', 'indian art'],
      },
      {
        name: 'Handcrafted Festive Brass & Marigold Floral Toran Door Bandhanwar',
        slug: 'handcrafted-festive-brass-marigold-floral-toran',
        tagline: 'Handmade auspicious entrance doorway hanging with golden bells & fabric roses',
        description: 'Welcome prosperity, harmony, and festive joy into your abode. Crafted with rich brocade fabrics, golden ghungroo bells, artificial velvet marigolds, and delicate pearl strings. Perfect for Diwali, weddings, and Griha Pravesh ceremonies.',
        category: 'Decorative Crafts',
        price: 1299,
        originalPrice: 1750,
        discountPercent: 26,
        rating: 4.9,
        numReviews: 22,
        images: [
          'https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&w=1000&q=80',
          'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?auto=format&fit=crop&w=1000&q=80',
        ],
        featuredImage: 'https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&w=1000&q=80',
        materials: ['Velvet & Raw Silk Fabric', 'Brass Ghungroos', 'Pearl Strings', 'Metal Rings'],
        dimensions: '38 inches width (standard door width)',
        leadTimeDays: 2,
        isCustomizable: true,
        customizationNote: 'Custom width measurements available for double doors.',
        inStock: true,
        countInStock: 14,
        isFeatured: false,
        isBestSeller: false,
        tags: ['toran', 'bandhanwar', 'festive decor', 'diwali', 'door hanging'],
      },
    ];

    const createdProducts = await Product.insertMany(productsData);
    console.log(`🎨 ${createdProducts.length} Handcrafted Products seeded successfully.`);

    // 4. Create Sample Customer Reviews
    const sampleReviews = [
      {
        product: createdProducts[0]._id,
        user: demoCustomer._id,
        name: 'Simran Sharma',
        city: 'New Delhi',
        rating: 5,
        comment: 'Ordered this for my sister’s wedding and everyone was in tears! The embroidery precision is magical. Manmeet even accommodated our special floral request. Packaging was so royal! ✨',
        isVerifiedPurchase: true,
      },
      {
        product: createdProducts[0]._id,
        name: 'Pooja Verma',
        city: 'Mumbai',
        rating: 5,
        comment: 'Absolutely stunning work! The thread colors matched our wedding outfits perfectly. 10/10 craftsmanship.',
        isVerifiedPurchase: true,
      },
      {
        product: createdProducts[3]._id, // Resin Clock
        name: 'Ananya Deshmukh',
        city: 'Pune',
        rating: 5,
        comment: 'The ocean waves look so realistic and glossy! The clock mechanism is completely silent. It has become the showstopper of my living room.',
        isVerifiedPurchase: true,
      },
      {
        product: createdProducts[6]._id, // Organza Dupatta
        name: 'Jaspreet Kaur',
        city: 'Chandigarh',
        rating: 5,
        comment: 'Wore this for my engagement ceremony. The lotus painting is so delicate and soft. Pure handcrafted perfection!',
        isVerifiedPurchase: true,
      },
      {
        product: createdProducts[9]._id, // Charcoal Portrait
        name: 'Rahul Malhotra',
        city: 'Bengaluru',
        rating: 5,
        comment: 'The likeness of my grandparents in the charcoal sketch was so accurate it took my breath away. Thank you Manmeet Creations!',
        isVerifiedPurchase: true,
      },
      {
        product: createdProducts[12]._id, // Explosion Box
        name: 'Kritika Sen',
        city: 'Kolkata',
        rating: 5,
        comment: 'My boyfriend was astonished when he opened the box. The photo quality and folding mechanisms are top tier.',
        isVerifiedPurchase: true,
      },
      {
        product: createdProducts[15]._id, // Spotify Plaque
        name: 'Rohan Mehra',
        city: 'Jaipur',
        rating: 5,
        comment: 'The wood LED base gives such a cozy aesthetic glow at night. The Spotify code scanned right away.',
        isVerifiedPurchase: true,
      },
      {
        product: createdProducts[18]._id, // Daisy Resin Pendant
        name: 'Sneha Roy',
        city: 'Hyderabad',
        rating: 5,
        comment: 'So lightweight and delicate! The gold chain hasn’t tarnished even after daily wear. Came in a gorgeous velvet pouch.',
        isVerifiedPurchase: true,
      },
    ];

    await Review.insertMany(sampleReviews);
    console.log(`💬 Sample Verified Customer Reviews seeded.`);

    // 5. Create Sample Orders
    const sampleOrder = await Order.create({
      orderId: 'MC-2026-8921',
      user: demoCustomer._id,
      customerInfo: {
        name: 'Simran Sharma',
        email: 'customer@gmail.com',
        phone: '+91 98123 45678',
      },
      shippingAddress: {
        street: 'Flat 402, Rosewood Heights, MG Road',
        city: 'Delhi',
        state: 'Delhi',
        postalCode: '110001',
        country: 'India',
      },
      orderItems: [
        {
          product: createdProducts[0]._id,
          name: createdProducts[0].name,
          image: createdProducts[0].featuredImage,
          price: createdProducts[0].price,
          quantity: 1,
          customNote: 'Names: Karan & Simran, Date: 24th Nov 2026',
        },
        {
          product: createdProducts[18]._id,
          name: createdProducts[18].name,
          image: createdProducts[18].featuredImage,
          price: createdProducts[18].price,
          quantity: 1,
          customNote: 'Gold finish chain',
        },
      ],
      paymentMethod: 'UPI / Online Payment',
      itemsPrice: 2898,
      shippingPrice: 0,
      totalAmount: 2898,
      isPaid: true,
      paidAt: new Date(),
      status: 'Confirmed',
      trackingNumber: 'BLUEDART-882194',
      adminNotes: 'Customer requested gift wrap with handwritten note.',
    });

    console.log(`📦 Demo Order created: ${sampleOrder.orderId}`);

    // 6. Create Sample Custom Orders (Bespoke requests)
    await CustomOrder.create([
      {
        requestId: 'REQ-4521',
        fullName: 'Meera Nambiar',
        phone: '+91 98450 11223',
        email: 'meera.n@gmail.com',
        whatWouldYouLike: 'Preserve my bridal kaleerein in an epoxy resin table clock',
        category: 'Resin Art',
        customizationDetails: 'I want my golden bridal kaleera tassels and red chooda bangles to be preserved inside a 12-inch round resin clock with white pearl background and gold roman numbers.',
        preferredSize: '12 inch diameter',
        budget: '₹4,000 - ₹6,000',
        requiredDate: '2026-10-15',
        referenceImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
        status: 'New Request',
      },
      {
        requestId: 'REQ-7819',
        fullName: 'Arjun Kapoor',
        phone: '+91 99201 88374',
        email: 'arjun.k@gmail.com',
        whatWouldYouLike: 'Hand-painted matching bridal sneakers for Sangeet',
        category: 'Fabric Painting',
        customizationDetails: 'White canvas platform sneakers painted with floral vines and "Bride 2026" calligraphed on the side heels.',
        preferredSize: 'UK Size 6',
        budget: '₹2,500 - ₹3,500',
        requiredDate: '2026-10-02',
        referenceImage: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80',
        status: 'Quote Sent',
        adminQuoteAmount: 2800,
        adminNotes: 'Spoke on WhatsApp, client approved design sketch.',
      },
    ]);

    // 7. Create Sample Contact Message
    await ContactMessage.create({
      name: 'Dr. Tanya Oberoi',
      email: 'tanya.oberoi@yahoo.com',
      phone: '+91 98200 44556',
      subject: 'Bulk Corporate Diwali Hampers Enquiry',
      message: 'Hello Manmeet! We are looking to order 50 customized resin coaster sets with our clinic logo for Diwali corporate gifting. Could you please share the bulk pricing and timeline?',
      isRead: false,
    });

    console.log('✨ All seed data created successfully!');
  } catch (error) {
    console.error('Error seeding data:', error);
  }
};

// If run directly via `node seeder.js`
if (process.argv[1].endsWith('seeder.js')) {
  connectDB().then(async () => {
    await seedData();
    process.exit(0);
  });
}
